import io
import json
import re
import zipfile
from pathlib import Path
from PIL import Image, ImageOps
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from .kdp import TRIMS


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-") or "coloring-book"


def _fit_image(image_path: Path, width_pt: float, height_pt: float, margin_pt: float = 36):
    im = Image.open(image_path).convert("RGB")
    max_w, max_h = width_pt - 2 * margin_pt, height_pt - 2 * margin_pt
    ratio = min(max_w / im.width, max_h / im.height)
    draw_w, draw_h = im.width * ratio, im.height * ratio
    x, y = (width_pt - draw_w) / 2, (height_pt - draw_h) / 2
    return im, x, y, draw_w, draw_h


def build_paperback_interior(image_paths: list[Path], output_pdf: Path, trim_name: str, title: str, publisher: str = "Little Joy Pages", blank_backs: bool = True):
    trim = TRIMS[trim_name]
    w, h = trim.width * 72, trim.height * 72
    output_pdf.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(output_pdf), pagesize=(w, h))
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(w / 2, h * .58, title)
    c.setFont("Helvetica", 12)
    c.drawCentredString(w / 2, h * .52, publisher)
    c.showPage()
    c.setFont("Helvetica", 9)
    c.drawString(54, 72, f"© {publisher}. All rights reserved.")
    c.showPage()
    for path in image_paths:
        im, x, y, dw, dh = _fit_image(path, w, h)
        c.drawImage(ImageReader(im), x, y, dw, dh, preserveAspectRatio=True, mask="auto")
        c.showPage()
        if blank_backs:
            c.showPage()
    c.save()
    return output_pdf


def build_listing_text(title: str, subtitle: str, description: str, keywords: list[str], trim: str, paperback: bool, kindle: bool) -> str:
    keys = "\n".join(f"{i+1}. {k}" for i, k in enumerate(keywords[:7]))
    outputs = ", ".join(x for x, on in [("Paperback", paperback), ("Kindle", kindle)] if on)
    return f"""LITTLE JOY PAGES — KDP LISTING\n\nTITLE\n{title}\n\nSUBTITLE\n{subtitle}\n\nDESCRIPTION\n{description}\n\nKEYWORDS\n{keys}\n\nEDITION OUTPUTS\n{outputs}\n\nPAPERBACK SETTINGS\nTrim size: {trim}\nInterior: Black & white\nPaper: White\nBleed: No bleed (default; verify artwork before upload)\nCover finish: Matte (recommended)\n\nAI CONTENT\nThe artwork generated by this app uses generative AI. Answer KDP's AI-generated-content disclosure accurately during publishing.\n\nFINAL CHECK\nRun the print files through KDP Previewer and the Kindle edition through Kindle Previewer before publishing. Verify current KDP categories, pricing, royalties, file requirements, and metadata choices at upload time.\n"""


def make_zip(project_dir: Path, output_zip: Path) -> Path:
    output_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in project_dir.rglob("*"):
            if p.is_file() and p.resolve() != output_zip.resolve():
                zf.write(p, p.relative_to(project_dir))
    return output_zip
